# Generated by Django 3.2.13 on 2022-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='average',
            old_name='average',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='average',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
